[CONNECTION:PROXY]
StartUp=0
Proxy=
[CONNECTION:SERIAL]
BaudRate=6
StopBits=0
FlowCtrl=0
Parity=0
DataBits=3
ComPort=0
[Information]
MinorVersion=0
MajorVersion=3
Description=Xshell Session Profile
[TRACE]
SockConn=1
SshLogin=0
SshTunneling=0
TelnetOptNego=0
[SessionInfo]
Version=5.1
[CONNECTION:SSH]
LaunchAuthAgent=1
KeyExchange=
ForwardToXmanager=1
Compression=0
KeyExchangeList=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256
NoTerminal=0
CipherList=aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael128-cbc,rijndael192-cbc,rijndael256-cbc,aes256-ctr,aes192-ctr,aes128-ctr,rijndael-cbc@lysator.liu.se
UseAuthAgent=0
MAC=
ForwardX11=0
InitRemoteDirectory=
VexMode=0
Cipher=
Display=localhost:0.0
FwdReqCount=0
InitLocalDirectory=
MACList=hmac-sha1,hmac-sha1-96,hmac-md5,hmac-md5-96,hmac-ripemd160,hmac-ripemd160@openssh.com
[USERINTERFACE]
NoQuickButton=0
ShowOnLinkBar=0
QuickCommand=
[CONNECTION:FTP]
Passive=1
InitRemoteDirectory=
InitLocalDirectory=
[TRANSFER]
FolderMethod=0
FolderPath=
AutoZmodem=1
SendFolderPath=
DuplMethod=0
[CONNECTION]
SendKeepAliveInterval=60
PasteDelay=0
Port=22
KeepAliveInterval=60
Protocol=SSH
Host=192.168.50.2
AutoReconnect=0
TCPKeepAlive=0
AutoReconnectLimit=0
Description=
KeepAliveString=
AutoReconnectInterval=30
SendKeepAlive=0
FtpPort=21
UseNaglesAlgorithm=0
IPV=0
KeepAlive=1
[TERMINAL]
CtrlAltIsAltGr=1
Rows=24
InitOriginMode=0
DisableBlinkingText=0
InitReverseMode=0
CodePage=65001
InitAutoWrapMode=1
InitEchoMode=0
Cols=80
ScrollBottomOnKeyPress=0
Type=xterm
CJKAmbiAsWide=1
DisableAlternateScreen=0
DisableTitleChange=0
ForceEraseOnDEL=0
ShiftForcesLocalUseOfMouse=1
InitInsertMode=0
FontLineCharacter=1
InitCursorMode=0
ScrollbackSize=1024
BackspaceSends=2
UseAltAsMeta=0
UseInitSize=0
IgnoreResizeRequest=0
DeleteSends=0
AltKeyMapPath=
DisableTermPrinting=0
ScrollBottomOnTermOutput=1
FontPowerLine=1
ScrollErasedText=1
KeyMap=0
RecvLLAsCRLF=0
EraseWithBackgroundColor=1
InitKeypadMode=0
InitNewlineMode=0
TerminalNameForEcho=
[TERMINAL:WINDOW]
ColorScheme=XTerm
LineSpace=0
CursorColor=65280
CursorBlinkInterval=600
TabColorType=0
CursorAppearance=0
TabColorOther=0
FontSize=9
CursorBlink=0
BoldMethod=2
CursorTextColor=0
FontFace=Courier New
CharSpace=0
MarginLeft=2
MarginBottom=2
MarginTop=2
MarginRight=2
[CONNECTION:TELNET]
XdispLoc=1
NegoMode=0
Display=$PCADDR:0.0
[CONNECTION:AUTHENTICATION]
Library=0
Passphrase=
UseInitScript=0
Delegation=0
TelnetLoginPrompt=ogin:
UseExpectSend=0
Password=BbwepmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=
RloginPasswordPrompt=assword:
TelnetPasswordPrompt=assword:
ExpectSend_Count=0
Method=0
ScriptPath=
UserKey=
UserName=root
[LOGGING]
FilePath=%n_%d_%t.log
Overwrite=1
Type=0
FileMethod=0
TermCode=0
AutoStart=0
Timestamp=0
Prompt=0
[CONNECTION:RLOGIN]
TermSpeed=38400
[CONNECTION:KEEPALIVE]
SendKeepAliveInterval=60
KeepAliveInterval=60
TCPKeepAlive=0
KeepAliveString=
SendKeepAlive=0
KeepAlive=1
